### ISSUE TITLE
Duration of the leases hardcoded?

### ISSUE THREAD

**Issue by bieldlucacn** [camelaissani/loca#50] opened 2021-01-12 19:23 UTC
Hey there! First of all I'm loving your project, it's really amazing and it's really gonna help me!
I do have a question tho, is the duration of the leases and how many leases there are hard-coded? or is there any way I can modify it?

**Comment by camelaissani** [comment] 2021-01-12 23:23
Hi, I'm delighted that you love my project thanks.
Unfortunately, my code is not yet generic enought to support other lease durations than the ones I need for my own purposes.

However it should not be complex to adapt it. You could follow the following steps:

On the back-end:
Adapt the form with your contract types: https://github.com/camelaissani/loca/blob/master/backend/pages/occupant/view/occupantform.ejs#L88-#L92

On the front-end:
Adapt the contract validator with your own lease durations here: https://github.com/camelaissani/loca/blob/master/frontend/js/formvalidators.js#L52

FYI, the contract validator is referenced here: https://github.com/camelaissani/loca/blob/master/frontend/js/occupant/occupantform.js#L70

Finaly, you have to change the rule which computes the "endDate" in case the "beginDate" has changed: https://github.com/camelaissani/loca/blob/master/frontend/js/occupant/occupantform.js#L408

**Comment by camelaissani** [comment] 2021-01-12 23:35
FYI, I have started a full rewrite of the UI with a more recent tech stack (NextJS/React - Formik - MaterialUI)

https://github.com/microrealestate/frontend

**Comment by camelaissani** [comment] 2021-05-24 20:32
This has been fixed in https://github.com/microrealestate/microrealestate.

Please open another ticket there if the issue is not fixed.
Thanks

**Closed by camelaissani** 2021-05-24 20:32 UTC
